### ISSUE TITLE
Unable to use in NET Framework applications, that require strong naming of all assemblies

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [mlockett42/litedb-async#23]
The main LiteDB library is signed with a String name snk, would it be possible to have this library signed too?
As it doesn't play well within .NET Framework applications, that require strong naming of all assemblies.

**Comment by mlockett42** [comment]
How can I set up an application which requires the LiteDB.Async library to be signed with a strong name?

I made a Dotnet Framework Console App put bypassTrustedAppStrongNames in the app.config file as per https://learn.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature and referenced LiteDB.Async v0.1.3 via nuget.

The console app compiles, run, including a call into LiteDB.Async but everything run file.

This would be nice so I can verify once signed the problem is fixed.

@Pete-PlaytimeSolutions

**Comment by Pete-PlaytimeSolutions** [comment]
Hi
One of our customers are using a commercial 3rd party framework that requires all libraries be signed.

It’s called “AddIn Express”, used for developing plug-ins for MS Word. 

It requires a purchased license to use. I don’t know how else to do it, without using a licensed version of that framework

**Comment by mlockett42** [comment]
I figured how to do it (must give the assembly referencing LiteDb.Async a strong name)

v0.1.4 in nuget should now work for you

**Comment by Pete-PlaytimeSolutions** [comment]
Thank you
